version: '3'
services: 
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes: 
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./src:/app
        