version: '3'
services: 
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes: 
            - ./docker/nginx/ananke.conf:/etc/nginx/conf.d/ananke.conf
            - ./src:/app
    php:
        build: 
            context: .
            args: 
                - APP_ENV=dev
            dockerfile: PHP.dockerfile
        volumes:
            - ./src:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'ananke'
            MYSQL_USER: 'ananke'
            MYSQL_PASSWORD: 'ananke'
            MYSQL_DATABASE: 'tutorial'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
volumes:
    mysqldata: {}
    
        