version: '3'
services: 
    web:
        image: nginx:latest
        ports:
            - "80:80"
        env_file: ./src/.env
        volumes: 
            - ./docker/nginx/ananke.conf:/etc/nginx/conf.d/ananke.conf
            - ./src:/app
    php:
        build: 
            context: .
            dockerfile: PHP.dockerfile
        volumes:
            - ./src:/app
    
        