version: '3'
services: 
    web:
        image: nginx:latest
        ports:
            - "80:80"
        env_file: ./src/.env
        volumes: 
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./src:/app
    php:
        image: php:fpm
        volumes:
            - ./src:/app
        